### ISSUE TITLE
Would be good for the code in the HEX files?

### ISSUE THREAD

**Issue by cyborgjon** [whaleygeek/mb_voice#1]
Hi there,

It would be useful to see the code being used in the HEX files? I can't see how you're sending information from the micro:bit via serial to then be read by OS X...

Cheers.

**Comment by whaleygeek** [comment]
Drag the hex file into python.microbit.org or makecode.microbit.org and you will see the source code. I cant remember which of those two editors I used but try both, one will work

**Comment by cyborgjon** [comment]
Great thanks - it was makecode.microbit.org that worked :)
